####################################################################################################
## FileName:             run-dotnet-nuget-push.yml
## Copyright:            Copyright © 2017-2019 Thomas Corwin, et al. All Rights Reserved.
## License:              https://github.com/tom-corwin/tcdfx/blob/master/LICENSE.md
####################################################################################################

parameters:
  projectName: ''

steps:

- task: NuGetCommand@2
  condition: and(eq( variables['Agent.OS'], 'Windows_NT' ), not(startsWith(variables['Build.SourceBranch'], 'ref/tags/v')))
  name: 'Run_NuGet_Push__WinNT_GitHub'
  displayName: 'Run `dotnet nuget push` (WinNT|GitHub)'
  continueOnError: false
  inputs:
    command: 'push'
    packagesToPush: '$(Build.Repository.LocalPath)\build\sources\${{ parameters.projectName }}\Release\pkg\*.nupkg'
    nugetFeedType: 'external'
    publishFeedCredentials: 'TCDFxGitHubFeed'

- task: NuGetCommand@2
  condition: and(ne( variables['Agent.OS'], 'Windows_NT' ), not(startsWith(variables['Build.SourceBranch'], 'ref/tags/v')))
  name: 'Run_NuGet_Push__Unix_GitHub'
  displayName: 'Run `dotnet nuget push` (Unix|GitHub)'
  continueOnError: false
  inputs:
    command: 'push'
    packagesToPush: '$(Build.Repository.LocalPath)/build/sources/${{ parameters.projectName }}/Release/pkg/*.nupkg'
    nugetFeedType: 'external'
    publishFeedCredentials: 'TCDFxGitHubFeed'

- task: NuGetCommand@2
  condition: and(eq( variables['Agent.OS'], 'Windows_NT' ), startsWith(variables['Build.SourceBranch'], 'ref/tags/v'))
  name: 'Run_NuGet_Push__WinNT_NuGet'
  displayName: 'Run `dotnet nuget push` (WinNT|NuGet)'
  continueOnError: false
  inputs:
    command: 'push'
    packagesToPush: '$(Build.Repository.LocalPath)\build\sources\${{ parameters.projectName }}\Release\pkg\*.nupkg'
    nugetFeedType: 'external'
    publishFeedCredentials: 'TCDFxNuGetFeed'

- task: NuGetCommand@2
  condition: and(ne( variables['Agent.OS'], 'Windows_NT' ), startsWith(variables['Build.SourceBranch'], 'ref/tags/v'))
  name: 'Run_NuGet_Push__Unix_NuGet'
  displayName: 'Run `dotnet nuget push` (Unix|NuGet)'
  continueOnError: false
  inputs:
    command: 'push'
    packagesToPush: '$(Build.Repository.LocalPath)/build/sources/${{ parameters.projectName }}/Release/pkg/*.nupkg'
    nugetFeedType: 'external'
    publishFeedCredentials: 'TCDFxNuGetFeed'