####################################################################################################
## FileName:             build.yml
## Copyright:            Copyright © 2017-2019 Thomas Corwin, et al. All Rights Reserved.
## License:              https://github.com/tom-corwin/tcdfx/blob/master/LICENSE.md
####################################################################################################

parameters:
  jobName: ''
  vmImage: ''
  projectName: ''
  configuration: ''

jobs:

- job: '${{ parameters.jobName }}'
  displayName: '${{ parameters.jobName }}'
  pool:
    vmImage: ${{ parameters.vmImage }}
  workspace:
    clean: all
  steps:
  - template: ../steps/install-dotnetcore-sdk.yml
  - template: ../steps/run-dotnet-restore.yml
    parameters:
      projectName: '${{ parameters.projectName }}'
      configuration: '${{ parameters.configuration }}'
  - template: ../steps/run-dotnet-build.yml
    parameters:
      projectName: '${{ parameters.projectName }}'
      configuration: '${{ parameters.configuration }}'