parameters:
  displayName: ''
  vmImage: 'windows-2019'
  configuration: 'Release'
  projectFile: '$(Build.Repository.LocalPath)\sources\$(Build.DefinitionName)\$(Build.DefinitionName).csproj'
  nupkgFile: '$(Build.Repository.LocalPath)\build\Release\$(Build.DefinitionName)\pkg\$(Build.DefinitionName)*.nupkg'

jobs:
- job: Publish_${{ parameters.displayName }}
  displayName: ${{ parameters.displayName }} (Publish)
  pool:
    vmImage: ${{ parameters.vmImage }}
  workspace:
    clean: all
  steps:
  - template: ../steps/install-dotnet-preview.yml
    parameters:
      sdkVersion: 3.0.100-preview5-011568
  - template: ../steps/dotnet-restore.yml
    parameters:
      configuration: ${{ parameters.configuration }}
      projectFile: ${{ parameters.projectFile }}
  - template: ../steps/dotnet-build.yml
    parameters:
      configuration: ${{ parameters.configuration }}
      projectFile: ${{ parameters.projectFile }}
  - template: ../steps/myget-push.yml
    parameters:
      nupkgFile: ${{ nupkgFile }}
  - template: ../steps/nuget-push.yml
    condition: startsWith('$(Build.SourceBranch)', 'ref/tags/')
    parameters:
      nupkgFile: ${{ nupkgFile }}