requestInfoDefaultTitles:
  - update readme.md
  - updates
  - fixes
requestInfoOn:
  pullRequest: true
  issue: true
requestInfoUserstoExclude:
  - tacdevel
requestInfoReplyComment: Thanks for contributing to this project! This project's maintainers would appreciate it if you could provide more information about this issue/pull request.
requestInfoLabelToAdd: needs-more-info
checkIssueTemplate: true
checkPullRequestTemplate: true