# Labels: define labels for Issues and Pull Requests
labels:
  - name: Priority:Critical
    color: D32F2F
  - name: Priority:High
    color: E64A19
  - name: Priority:Medium
    color: FBC02D
  - name: Priority:Low
    color: 388E3C
  - name: Status:Approved
    color: 388E3C
  - name: Status:Rejected
    color: D32F2F
  - name: Status:Available
    color: 689F38
  - name: Status:Inactive
    color: 616161
  - name: Status:Blocked
    color: D32F2F
  - name: Status:Pending
    color: D32F2F
  - name: Status:InProgress
    color: FBC02D
  - name: Status:AwaitingReview
    color: FFA000
  - name: Status:AwaitingRevision
    color: F57C00
  - name: Status:OnHold
    color: D32F2F
  - name: Status:WillNotFix
    color: 616161
  - name: Type:Bug
    color: D32F2F
  - name: Type:Question
    color: 512DA8
  - name: Type:Discussion
    color: 512DA8
  - name: Type:Documentation
    color: 1976D2
  - name: Type:Feature
    color: 00796B
  - name: Type:Fix
    color: 0097A7
  - name: Type:Enhancement
    color: 0288D1
  - name: Type:Security
    color: D32F2F
  - name: Type:Testing
    color: AFB42B
  - name: Type:Other
    color: 5D4037
  - name: Type:CI
    color: 303F9F
  - name: Type:Invalid
    color: D32F2F
  - name: Type:Duplicate
    color: 616161
  - name: Type:External
    color: D32F2F
  - name: Type:Infrastructure
    color: 1976D2
  - name: Platform:All
    color: 455A64
  - name: Platform:Windows
    color: 455A64
  - name: Platform:Linux
    color: 455A64
  - name: Platform:MacOS
    color: 455A64
  - name: Platform:Other
    color: 455A64
  - name: Meta:GoodFirstIssue
    color: 689F38