# Labels: define labels for Issues and Pull Requests
labels:
  - name: Priority:Critical
  - name: Priority:High
  - name: Priority:Medium
  - name: Priority:Low
  - name: Status:Approved
  - name: Status:Rejected
  - name: Status:Available
  - name: Status:Inactive
  - name: Status:Blocked
  - name: Status:Pending
  - name: Status:InProgress
  - name: Status:AwaitingReview
  - name: Status:AwaitingRevision
  - name: Status:OnHold
  - name: Status:WillNotFix
  - name: Type:Bug
  - name: Type:Question
  - name: Type:Discussion
  - name: Type:Documentation
  - name: Type:Feature
  - name: Type:Fix
  - name: Type:Enhancement
  - name: Type:Security
  - name: Type:Testing
  - name: Type:Other
  - name: Type:CI
  - name: Type:Invalid
  - name: Type:Duplicate
  - name: Type:External
  - name: Type:Infrastructure
  - name: Platform:All
  - name: Platform:Windows
  - name: Platform:Linux
  - name: Platform:MacOS
  - name: Platform:Other
  - name: Meta:GoodFirstIssue