####################################################################################################
## FileName:             azure-pipelines.yml
## Copyright:            Copyright © 2017-2019 Thomas Corwin, et al. All Rights Reserved.
## License:              https://github.com/tom-corwin/tcdfx/blob/master/LICENSE.md
####################################################################################################

## Global Configuration
################################################################################

name: $(Date:yyMMdd)$(Rev:rrr)

trigger:
  batch: false
  branches:
    include:
    - master
    - feature/*
    - hotfix/*
    - ref/tags/v*
  paths:
    exclude:
    - "*.md"
    - ".gitignore"
    - ".gitattributes"
    - ".editorconfig"
    - ".github/*"

pr:
  autoCancel: true
  branches:
    include:
    - master
    - feature/*
    - hotfix/*
  paths:
    exclude:
    - "*.md"
    - ".gitignore"
    - ".gitattributes"
    - ".editorconfig"
    - ".github/*"

jobs:

## Build Jobs
################################################################################
- template: ./.azure-pipelines/jobs/build.yml
  parameters:
    osName: 'Ubuntu1604'
    vmImage: 'ubuntu-16.04'
    configuration: 'Debug'
- template: ./.azure-pipelines/jobs/build.yml
  parameters:
    osName: 'Ubuntu1604'
    vmImage: 'ubuntu-16.04'
    configuration: 'Release'
- template: ./.azure-pipelines/jobs/build.yml
  parameters:
    osName: 'macOS1013'
    vmImage: 'macOS-10.13'
    configuration: 'Debug'
- template: ./.azure-pipelines/jobs/build.yml
  parameters:
    osName: 'macOS1013'
    vmImage: 'macOS-10.13'
    configuration: 'Release'
- template: ./.azure-pipelines/jobs/build.yml
  parameters:
    osName: 'macOS1014'
    vmImage: 'macOS-10.14'
    configuration: 'Debug'
- template: ./.azure-pipelines/jobs/build.yml
  parameters:
    osName: 'macOS1014'
    vmImage: 'macOS-10.14'
    configuration: 'Release'
- template: ./.azure-pipelines/jobs/build.yml
  parameters:
    osName: 'Windows81'
    vmImage: 'vs2015-win2012r2'
    configuration: 'Debug'
- template: ./.azure-pipelines/jobs/build.yml
  parameters:
    osName: 'Windows81'
    vmImage: 'vs2015-win2012r2'
    configuration: 'Release'
- template: ./.azure-pipelines/jobs/build.yml
  parameters:
    osName: 'Windows10'
    vmImage: 'windows-2019'
    configuration: 'Debug'
- template: ./.azure-pipelines/jobs/build.yml
  parameters:
    osName: 'Windows10'
    vmImage: 'windows-2019'
    configuration: 'Release'

## Publish Jobs
################################################################################
- template: ./.azure-pipelines/jobs/publish.yml