#TODO: Simplify jobs/tasks a bit with templates.
#TODO: Add trigger/pr excludes .md, .github/, tests/, and examples/.

name: build-$(Date:yyyyMMdd)$(Rev:.rr)
resources:
- repo: self

trigger:
  batch: false
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'

pr:
  autoCancel: true
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'

jobs:
- job: windows2012r2_debug
  displayName: Windows 2012R2 Debug
  condition: succeeded()
  pool:
    vmImage: 'vs2015-win2012r2'
  workspace:
    clean: all
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core'
    inputs:
      version: 3.0.100-preview5-011568
      includePreviewVersions: true
  - script: dotnet restore $(Build.Repository.LocalPath)\source\$(Build.DefinitionName)\$(Build.DefinitionName).csproj --force --no-dependencies --disable-parallel
    displayName: 'dotnet restore ($(Build.DefinitionName))'
  - script: dotnet build $(Build.Repository.LocalPath)\source\$(Build.DefinitionName)\$(Build.DefinitionName).csproj -c Debug --force --no-dependencies --nologo --no-restore --version-suffix $(Build.BuildNumber)
    displayName: 'dotnet build ($(Build.DefinitionName))'
- job: windows2012r2_release
  displayName: Windows 2012R2 Release
  condition: succeeded()
  pool:
    vmImage: 'vs2015-win2012r2'
  workspace:
    clean: all
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core'
    inputs:
      version: 3.0.100-preview5-011568
      includePreviewVersions: true
  - script: dotnet restore $(Build.Repository.LocalPath)\source\$(Build.DefinitionName)\$(Build.DefinitionName).csproj --force --no-dependencies --disable-parallel
    displayName: 'dotnet restore ($(Build.DefinitionName))'
  - script: dotnet build $(Build.Repository.LocalPath)\source\$(Build.DefinitionName)\$(Build.DefinitionName).csproj -c Release --force --no-dependencies --nologo --no-restore --version-suffix $($(Build.BuildNumber))
    displayName: 'dotnet build ($(Build.DefinitionName))'
- job: windows2016_debug
  displayName: Windows 2016 Debug
  condition: succeeded()
  pool:
    vmImage: 'vs2017-win2016'
  workspace:
    clean: all
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core'
    inputs:
      version: 3.0.100-preview5-011568
      includePreviewVersions: true
  - script: dotnet restore $(Build.Repository.LocalPath)\source\$(Build.DefinitionName)\$(Build.DefinitionName).csproj --force --no-dependencies --disable-parallel
    displayName: 'dotnet restore ($(Build.DefinitionName))'
  - script: dotnet build $(Build.Repository.LocalPath)\source\$(Build.DefinitionName)\$(Build.DefinitionName).csproj -c Debug --force --no-dependencies --nologo --no-restore --version-suffix $($(Build.BuildNumber))
    displayName: 'dotnet build ($(Build.DefinitionName))'
- job: windows2016_release
  displayName: Windows 2016 Release
  condition: succeeded()
  pool:
    vmImage: 'vs2017-win2016'
  workspace:
    clean: all
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core'
    inputs:
      version: 3.0.100-preview5-011568
      includePreviewVersions: true
  - script: dotnet restore $(Build.Repository.LocalPath)\source\$(Build.DefinitionName)\$(Build.DefinitionName).csproj --force --no-dependencies --disable-parallel
    displayName: 'dotnet restore ($(Build.DefinitionName))'
  - script: dotnet build $(Build.Repository.LocalPath)\source\$(Build.DefinitionName)\$(Build.DefinitionName).csproj -c Release --force --no-dependencies --nologo --no-restore --version-suffix $($(Build.BuildNumber))
    displayName: 'dotnet build ($(Build.DefinitionName))'
- job: windows2019_debug
  displayName: Windows 2019 Debug
  condition: succeeded()
  pool:
    vmImage: 'windows-2019'
  workspace:
    clean: all
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core'
    inputs:
      version: 3.0.100-preview5-011568
      includePreviewVersions: true
  - script: dotnet restore $(Build.Repository.LocalPath)\source\$(Build.DefinitionName)\$(Build.DefinitionName).csproj --force --no-dependencies --disable-parallel
    displayName: 'dotnet restore ($(Build.DefinitionName))'
  - script: dotnet build $(Build.Repository.LocalPath)\source\$(Build.DefinitionName)\$(Build.DefinitionName).csproj -c Debug --force --no-dependencies --nologo --no-restore --version-suffix $($(Build.BuildNumber))
    displayName: 'dotnet build ($(Build.DefinitionName))'
- job: windows2019_release
  displayName: Windows 2019 Release
  condition: succeeded()
  pool:
    vmImage: 'windows-2019'
  workspace:
    clean: all
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core'
    inputs:
      version: 3.0.100-preview5-011568
      includePreviewVersions: true
  - script: dotnet restore $(Build.Repository.LocalPath)\source\$(Build.DefinitionName)\$(Build.DefinitionName).csproj --force --no-dependencies --disable-parallel
    displayName: 'dotnet restore ($(Build.DefinitionName))'
  - script: dotnet build $(Build.Repository.LocalPath)\source\$(Build.DefinitionName)\$(Build.DefinitionName).csproj -c Release --force --no-dependencies --nologo --no-restore --version-suffix $($(Build.BuildNumber))
    displayName: 'dotnet build ($(Build.DefinitionName))'
- job: macos1013_debug
  displayName: macOS 10.13 Debug
  condition: succeeded()
  pool:
    vmImage: 'macOS-10.13'
  workspace:
    clean: all
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core'
    inputs:
      version: 3.0.100-preview5-011568
      includePreviewVersions: true
  - script: dotnet restore $(Build.Repository.LocalPath)\source\$(Build.DefinitionName)\$(Build.DefinitionName).csproj --force --no-dependencies --disable-parallel
    displayName: 'dotnet restore ($(Build.DefinitionName))'
  - script: dotnet build $(Build.Repository.LocalPath)\source\$(Build.DefinitionName)\$(Build.DefinitionName).csproj -c Debug --force --no-dependencies --nologo --no-restore --version-suffix $($(Build.BuildNumber))
    displayName: 'dotnet build ($(Build.DefinitionName))'
- job: macos1013_release
  displayName: macOS 10.13 Release
  condition: succeeded()
  pool:
    vmImage: 'macOS-10.13'
  workspace:
    clean: all
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core'
    inputs:
      version: 3.0.100-preview5-011568
      includePreviewVersions: true
  - script: dotnet restore $(Build.Repository.LocalPath)\source\$(Build.DefinitionName)\$(Build.DefinitionName).csproj --force --no-dependencies --disable-parallel
    displayName: 'dotnet restore ($(Build.DefinitionName))'
  - script: dotnet build $(Build.Repository.LocalPath)\source\$(Build.DefinitionName)\$(Build.DefinitionName).csproj -c Release --force --no-dependencies --nologo --no-restore --version-suffix $($(Build.BuildNumber))
    displayName: 'dotnet build ($(Build.DefinitionName))'
- job: macos1014_debug
  displayName: macOS 10.14 Debug
  condition: succeeded()
  pool:
    vmImage: 'macOS-10.14'
  workspace:
    clean: all
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core'
    inputs:
      version: 3.0.100-preview5-011568
      includePreviewVersions: true
  - script: dotnet restore $(Build.Repository.LocalPath)\source\$(Build.DefinitionName)\$(Build.DefinitionName).csproj --force --no-dependencies --disable-parallel
    displayName: 'dotnet restore ($(Build.DefinitionName))'
  - script: dotnet build $(Build.Repository.LocalPath)\source\$(Build.DefinitionName)\$(Build.DefinitionName).csproj -c Debug --force --no-dependencies --nologo --no-restore --version-suffix $($(Build.BuildNumber))
    displayName: 'dotnet build ($(Build.DefinitionName))'
- job: macos1014_release
  displayName: macOS 10.14 Release
  condition: succeeded()
  pool:
    vmImage: 'macOS-10.14'
  workspace:
    clean: all
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core'
    inputs:
      version: 3.0.100-preview5-011568
      includePreviewVersions: true
  - script: dotnet restore $(Build.Repository.LocalPath)\source\$(Build.DefinitionName)\$(Build.DefinitionName).csproj --force --no-dependencies --disable-parallel
    displayName: 'dotnet restore ($(Build.DefinitionName))'
  - script: dotnet build $(Build.Repository.LocalPath)\source\$(Build.DefinitionName)\$(Build.DefinitionName).csproj -c Release --force --no-dependencies --nologo --no-restore --version-suffix $($(Build.BuildNumber))
    displayName: 'dotnet build ($(Build.DefinitionName))'
- job: ubuntu1604_debug
  displayName: Ubuntu 16.04 Debug
  condition: succeeded()
  pool:
    vmImage: 'ubuntu-16.04'
  workspace:
    clean: all
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core'
    inputs:
      version: 3.0.100-preview5-011568
      includePreviewVersions: true
  - script: dotnet restore $(Build.Repository.LocalPath)\source\$(Build.DefinitionName)\$(Build.DefinitionName).csproj --force --no-dependencies --disable-parallel
    displayName: 'dotnet restore ($(Build.DefinitionName))'
  - script: dotnet build $(Build.Repository.LocalPath)\source\$(Build.DefinitionName)\$(Build.DefinitionName).csproj -c Debug --force --no-dependencies --nologo --no-restore --version-suffix $($(Build.BuildNumber))
    displayName: 'dotnet build ($(Build.DefinitionName))'
- job: ubuntu1604_release
  displayName: Ubuntu 16.04 Release
  condition: succeeded()
  pool:
    vmImage: 'ubuntu-16.04'
  workspace:
    clean: all
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core'
    inputs:
      version: 3.0.100-preview5-011568
      includePreviewVersions: true
  - script: dotnet restore $(Build.Repository.LocalPath)\source\$(Build.DefinitionName)\$(Build.DefinitionName).csproj --force --no-dependencies --disable-parallel
    displayName: 'dotnet restore ($(Build.DefinitionName))'
  - script: dotnet build $(Build.Repository.LocalPath)\source\$(Build.DefinitionName)\$(Build.DefinitionName).csproj -c Release --force --no-dependencies --nologo --no-restore --version-suffix $($(Build.BuildNumber))
    displayName: 'dotnet build ($(Build.DefinitionName))'