####################################################################################################
## FileName:             azure-pipelines.yml
## Copyright:            Copyright © 2017-2019 Thomas Corwin, et al. All Rights Reserved.
## License:              https://github.com/tom-corwin/tcdfx/blob/master/LICENSE.md
####################################################################################################

#TODO: Set up tests once finished.
#TODO: Set up documentation generation once finished.
#TODO: Set up CI builds to push to MyGet.
#TODO: Set up tagged/release builds to push to NuGet.

## General Configuration
name: $(Date:yyyyMMdd)$(Rev:-rrr) # Build.BuildNumber
resources:
- repo: self

## Pipeline Triggers
trigger:
  batch: false
  branches:
    include:
    - '*'
  tags:
    include:
    - v*
  paths:
    exclude:
    - "*.md"
    - ".gitignore"
    - ".gitattributes"
    - ".editorconfig"
    - ".github/*"
pr:
  autoCancel: true
  branches:
    include:
    - '*'
  paths:
    exclude:
    - "*.md"
    - ".gitignore"
    - ".gitattributes"
    - ".editorconfig"
    - ".github/*"

## Build Jobs
jobs:
- template: .azure-pipelines/jobs/build.yml
  parameters:
    displayName: 'Windows 8.1'
    vmImage: 'vs2015-win2012r2'
    configuration: 'Debug'
- template: .azure-pipelines/jobs/build.yml
  parameters:
    displayName: 'Windows 8.1'
    vmImage: 'vs2015-win2012r2'
    configuration: 'Release'
- template: .azure-pipelines/jobs/build.yml
  parameters:
    displayName: 'Windows 10 v1803'
    vmImage: 'vs2017-win2016'
    configuration: 'Debug'
- template: .azure-pipelines/jobs/build.yml
  parameters:
    displayName: 'Windows 10 v1803'
    vmImage: 'vs2017-win2016'
    configuration: 'Release'
- template: .azure-pipelines/jobs/build.yml
  parameters:
    displayName: 'Windows 10 v1809'
    vmImage: 'windows-2019'
    configuration: 'Debug'
- template: .azure-pipelines/jobs/build.yml
  parameters:
    displayName: 'Windows 10 v1809'
    vmImage: 'windows-2019'
    configuration: 'Release'
- template: .azure-pipelines/jobs/build.yml
  parameters:
    displayName: 'macOS 10.13'
    vmImage: 'macOS-10.13'
    configuration: 'Debug'
- template: .azure-pipelines/jobs/build.yml
  parameters:
    displayName: 'macOS 10.13'
    vmImage: 'macOS-10.13'
    configuration: 'Release'
- template: .azure-pipelines/jobs/build.yml
  parameters:
    displayName: 'macOS 10.14'
    vmImage: 'macOS-10.14'
    configuration: 'Debug'
- template: .azure-pipelines/jobs/build.yml
  parameters:
    displayName: 'macOS 10.14'
    vmImage: 'macOS-10.14'
    configuration: 'Release'
- template: .azure-pipelines/jobs/build.yml
  parameters:
    displayName: 'Ubuntu 16.04'
    vmImage: 'ubuntu-16.04'
    configuration: 'Debug'
- template: .azure-pipelines/jobs/build.yml
  parameters:
    displayName: 'Ubuntu 16.04'
    vmImage: 'ubuntu-16.04'
    configuration: 'Release'