variables:
  build.buildNumber: $(Date:yyyyMMdd)$(Rev:.rr)
  build.configuration: Release
  build.projectName: TCD.Drawing.Common

name: $(build.buildNumber)

resources:
  - repo: self

trigger:
  - master

jobs:
- job: macOS
  pool:
    vmImage: 'macOS-10.13'

  steps:
  - script: |
      dotnet restore --disable-parallel --force
      dotnet build -c $(build.configuration) --no-restore -p:TCDFxVersionSuffix=$(build.buildNumber)

    workingDirectory: source/$(build.projectName)
    displayName: Build

- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - script: |
      dotnet restore --disable-parallel --force
      dotnet build -c $(build.configuration) --no-restore -p:TCDFxVersionSuffix=$(build.buildNumber)

    workingDirectory: source/$(build.projectName)
    displayName: Build

- job: Windows
  pool:
    vmImage: 'windows-2019'
    
  steps:
  - script: |
      dotnet restore --disable-parallel --force
      dotnet build -c $(build.configuration) --no-restore -p:TCDFxVersionSuffix=$(build.buildNumber)
      dotnet nuget push ..\..\build\$(build.projectName)\pkg\ -k $(NuGet.PushKey) -s $(NuGet.PushUrl) --no-service-endpoint

    workingDirectory: source\$(build.projectName)
    displayName: Build and Push Package