####################################################################################################
## FileName:             build.yml
## Copyright:            Copyright © 2017-2019 Thomas Corwin, et al. All Rights Reserved.
## License:              https://github.com/tom-corwin/tcdfx/blob/master/LICENSE.md
####################################################################################################

parameters:
  osName: ''
  vmImage: ''
  configuration: ''

jobs:

- job: 'TCDFxCore_${{ parameters.osName }}_${{ parameters.configuration }}'
  displayName: 'TCDFxCore_${{ parameters.osName }}_${{ parameters.configuration }}'
  pool:
    vmImage: ${{ parameters.vmImage }}
  workspace:
    clean: all
  steps:
  - template: ../steps/install-dotnetcore-sdk.yml
  - template: ../steps/run-dotnet-restore.yml
    parameters:
      projectName: 'TCDFx.Core'
      configuration: '${{ parameters.configuration }}'
  - template: ../steps/run-dotnet-build.yml
    parameters:
      projectName: 'TCDFx.Core'
      configuration: '${{ parameters.configuration }}'

- job: 'TCDFxUI_${{ parameters.osName }}_${{ parameters.configuration }}'
  dependsOn:
  - TCDFxCore_${{ parameters.osName }}_${{ parameters.configuration }}
  displayName: 'TCDFxUI_${{ parameters.osName }}_${{ parameters.configuration }}'
  pool:
    vmImage: ${{ parameters.vmImage }}
  workspace:
    clean: all
  steps:
  - template: ../steps/install-dotnetcore-sdk.yml
  - template: ../steps/run-dotnet-restore.yml
    parameters:
      projectName: 'TCDFx.UI'
      configuration: '${{ parameters.configuration }}'
  - template: ../steps/run-dotnet-build.yml
    parameters:
      projectName: 'TCDFx.UI'
      configuration: '${{ parameters.configuration }}'