parameters:
  platform: ''
  vmImage: ''
  configuration: ''
  versionSuffix: '$(Build.BuildNumber)'
  dotnetVersion: '3.0.100-preview6-012264'

jobs:
# TCDFxCore_*
- job: TCDFxCore_${{ parameters.platform }}_${{ parameters.configuration }}
  displayName: TCDFxCore_${{ parameters.platform }}_${{ parameters.configuration }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  workspace:
    clean: all
  steps:
  - template: ./steps/checkout-sources.yml
  - template: ./steps/install-tcdfx-dev-deps.yml
    parameters:
      dotnetVersion: '${{ parameters.dotnetVersion }}'
  - template: ./steps/build-tcdfx-project.yml
    parameters:
      configuration: '${{ parameters.configuration }}'
      projectName: 'TCDFx.Core'
      versionSuffix: '${{ parameters.versionSuffix }}'
# - template: ./make-intermediate-pkg.yml
# - template: ./push-pkg-myget.yml
# - template: ./push-pkg-nuget.yml

# TCDFxUI_*
- job: TCDFxUI_${{ parameters.platform }}_${{ parameters.configuration }}
  displayName: TCDFxUI_${{ parameters.platform }}_${{ parameters.configuration }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  workspace:
    clean: all
  steps:
  - template: ./steps/checkout-sources.yml
  - template: ./steps/install-libui-dev-deps.yml
  - template: ./steps/install-tcdfx-dev-deps.yml
    parameters:
      dotnetVersion: '${{ parameters.dotnetVersion }}'
  - template: ./steps/build-libui-shared-libs.yml
  - template: ./steps/build-tcdfx-project.yml
    parameters:
      configuration: '${{ parameters.configuration }}'
      projectName: 'TCDFx.UI'
      versionSuffix: '${{ parameters.versionSuffix }}'
# - template: ./make-intermediate-pkg.yml
# - template: ./push-pkg-myget.yml
# - template: ./push-pkg-nuget.yml