parameters:
  displayName: ''
  vmImage: ''
  configuration: ''

jobs:
- job: ${{ parameters.displayName }}${{ parameters.configuration }}
  displayName: ${{ parameters.displayName }}(${{ parameters.configuration }})
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  pool:
    vmImage: ${{ parameters.vmImage }}
  workspace:
    clean: all
  steps:
  - template: ./build-init.yml
    parameters:
      sdkVersion: 3.0.100-preview5-011568
      isPreview: true
  - template: ./build-run.yml
    parameters:
      configuration: ${{ parameters.configuration }}
      projectFile: $(Build.Repository.LocalPath)\sources\$(Build.DefinitionName)\$(Build.DefinitionName).csproj
- job: ${{ parameters.displayName }}${{ parameters.configuration }}
  displayName: ${{ parameters.displayName }}(${{ parameters.configuration }})
  condition: ne( variables['Agent.OS'], 'Windows_NT' )
  pool:
    vmImage: ${{ parameters.vmImage }}
  workspace:
    clean: all
  steps:
  - template: ./build-init.yml
    parameters:
      sdkVersion: 3.0.100-preview5-011568
      isPreview: true
  - template: ./build-run.yml
    parameters:
      configuration: ${{ parameters.configuration }}
      projectFile: $(Build.Repository.LocalPath)/sources/$(Build.DefinitionName)/$(Build.DefinitionName).csproj