parameters:
  displayName: 'Windows10v1809'
  vmImage: 'windows-2019'
  nupkgFile: ''

jobs:
- job: Publish_${{ parameters.displayName }}
  displayName: ${{ parameters.displayName }} (Publish)
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  pool:
    vmImage: ${{ parameters.vmImage }}
  workspace:
    clean: all
  steps:
  - template: ./build-init.yml
    parameters:
      sdkVersion: 3.0.100-preview5-011568
      isPreview: true
  - template: ./build-run.yml
    parameters:
      configuration: ${{ parameters.configuration }}
      includeVersionSuffix: false
  - template: ./publish-packages.yml
    parameters:
      nupkgFile: $(Build.Repository.LocalPath)\build\sources\$(Build.DefinitionName)\Release\pkg\$(Build.DefinitionName)*.nupkg
- job: Publish_${{ parameters.displayName }}
  displayName: ${{ parameters.displayName }} (Publish)
  condition: ne( variables['Agent.OS'], 'Windows_NT' )
  pool:
    vmImage: ${{ parameters.vmImage }}
  workspace:
    clean: all
  steps:
  - template: ./build-init.yml
    parameters:
      sdkVersion: 3.0.100-preview5-011568
      isPreview: true
  - template: ./build-run.yml
    parameters:
      configuration: ${{ parameters.configuration }}
      includeVersionSuffix: false
  - template: ./publish-packages.yml
    parameters:
      nupkgFile: $(Build.Repository.LocalPath)/build/sources/$(Build.DefinitionName)/Release/pkg/$(Build.DefinitionName)*.nupkg